"""product profile table

Revision ID: 4ed6131cf1c4
Revises: fad6e8d9ca70
Create Date: 2026-10-02 18:11:53.161634
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '4ed6131cf1c4'
down_revision: str | None = 'fad6e8d9ca70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_profiles',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('sender_email', sa.String(length=320), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('research_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_profiles'))
    )
    op.create_index('uq_product_profiles_single_active', 'product_profiles', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_product_profiles_single_active', table_name='product_profiles', postgresql_where=sa.text('is_active'))
    op.drop_table('product_profiles')
    # ### end Alembic commands ###
