"""user roles and per-user ownership

Revision ID: b601b5346fa3
Revises: 4ed6131cf1c4
Create Date: 2026-10-02 19:31:02.415757

Adjusted from the autogenerated version in three ways:

  * `users.role` is added with a server default. Autogenerate emitted a plain
    NOT NULL column, which cannot be added to a table that already has rows.
  * The CHECK constraint on the role vocabulary is added explicitly;
    autogenerate does not pick up constraints declared in __table_args__ on an
    existing table.
  * Existing rows are backfilled. Without it every lead, ICP and campaign
    created before this migration would have a NULL owner and disappear from
    every member's console.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b601b5346fa3"
down_revision: str | None = "4ed6131cf1c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("role", sa.String(length=20), nullable=False, server_default="member"),
    )
    op.create_check_constraint(
        "ck_users_role_valid", "users", "role IN ('admin', 'member')"
    )

    for table in ("campaigns", "icps", "leads"):
        op.add_column(table, sa.Column("owner_id", sa.Uuid(), nullable=True))
        op.create_index(op.f(f"ix_{table}_owner_id"), table, ["owner_id"], unique=False)
        op.create_foreign_key(
            op.f(f"fk_{table}_owner_id_users"),
            table,
            "users",
            ["owner_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # The first account becomes the administrator and inherits everything that
    # existed before ownership was a concept, so an upgrade of a live database
    # leaves nothing stranded.
    op.execute(
        """
        UPDATE users SET role = 'admin'
        WHERE id = (SELECT id FROM users ORDER BY created_at LIMIT 1)
        """
    )
    for table in ("campaigns", "icps", "leads"):
        op.execute(
            f"""
            UPDATE {table} SET owner_id = (
                SELECT id FROM users WHERE role = 'admin' ORDER BY created_at LIMIT 1
            )
            WHERE owner_id IS NULL
            """
        )


def downgrade() -> None:
    for table in ("leads", "icps", "campaigns"):
        op.drop_constraint(op.f(f"fk_{table}_owner_id_users"), table, type_="foreignkey")
        op.drop_index(op.f(f"ix_{table}_owner_id"), table_name=table)
        op.drop_column(table, "owner_id")

    op.drop_constraint("ck_users_role_valid", "users", type_="check")
    op.drop_column("users", "role")
