"""initial schema

Revision ID: fad6e8d9ca70
Revises: 
Create Date: 2026-10-02 16:49:20.418170
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'fad6e8d9ca70'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('employee_count IS NULL OR employee_count >= 0', name=op.f('ck_companies_employee_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('domain', name='uq_companies_domain')
    )
    op.create_index('ix_companies_industry_region', 'companies', ['industry', 'region'], unique=False)
    op.create_table('icps',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('employee_min', sa.Integer(), nullable=True),
    sa.Column('employee_max', sa.Integer(), nullable=True),
    sa.Column('titles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('employee_min IS NULL OR employee_max IS NULL OR employee_min <= employee_max', name=op.f('ck_icps_employee_range_ordered')),
    sa.CheckConstraint('employee_min IS NULL OR employee_min >= 0', name=op.f('ck_icps_employee_min_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_icps'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icp_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('sender_email', sa.String(length=320), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'paused', 'completed')", name=op.f('ck_campaigns_status_valid')),
    sa.ForeignKeyConstraint(['icp_id'], ['icps.id'], name=op.f('fk_campaigns_icp_id_icps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_icp_id'), 'campaigns', ['icp_id'], unique=False)
    op.create_table('discovery_runs',
    sa.Column('icp_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('companies_created', sa.Integer(), nullable=False),
    sa.Column('leads_created', sa.Integer(), nullable=False),
    sa.Column('leads_rejected', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('agent_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name=op.f('ck_discovery_runs_status_valid')),
    sa.CheckConstraint('requested_count BETWEEN 1 AND 50', name=op.f('ck_discovery_runs_requested_count_in_range')),
    sa.ForeignKeyConstraint(['icp_id'], ['icps.id'], name=op.f('fk_discovery_runs_icp_id_icps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_runs'))
    )
    op.create_index(op.f('ix_discovery_runs_icp_id'), 'discovery_runs', ['icp_id'], unique=False)
    op.create_table('leads',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('discovery_run_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('seniority', sa.String(length=60), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email IS NULL OR position('@' in email) > 1", name=op.f('ck_leads_email_shape')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leads_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_runs.id'], name=op.f('fk_leads_discovery_run_id_discovery_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('company_id', 'email', name='uq_leads_company_id_email')
    )
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_discovery_run_id'), 'leads', ['discovery_run_id'], unique=False)
    op.create_index('ix_leads_job_title', 'leads', ['job_title'], unique=False)
    op.create_table('campaign_leads',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_leads_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_campaign_leads_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_leads')),
    sa.UniqueConstraint('campaign_id', 'lead_id', name='uq_campaign_leads_campaign_id_lead_id'),
    sa.UniqueConstraint('unsubscribe_token', name=op.f('uq_campaign_leads_unsubscribe_token'))
    )
    op.create_index(op.f('ix_campaign_leads_campaign_id'), 'campaign_leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_leads_lead_id'), 'campaign_leads', ['lead_id'], unique=False)
    op.create_table('lead_scores',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'queued', 'sent', 'delivered', 'opened', 'replied', 'unsubscribed', 'bounced')", name=op.f('ck_lead_scores_status_valid')),
    sa.CheckConstraint('fit_score >= 0 AND engagement_score >= 0', name=op.f('ck_lead_scores_components_non_negative')),
    sa.CheckConstraint('total_score BETWEEN 0 AND 100', name=op.f('ck_lead_scores_total_score_in_range')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_scores_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_scores')),
    sa.UniqueConstraint('lead_id', name=op.f('uq_lead_scores_lead_id'))
    )
    op.create_index(op.f('ix_lead_scores_status'), 'lead_scores', ['status'], unique=False)
    op.create_index(op.f('ix_lead_scores_total_score'), 'lead_scores', ['total_score'], unique=False)
    op.create_table('suppressed_emails',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('source_lead_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("reason IN ('unsubscribed', 'bounced', 'manual', 'reply_opt_out')", name=op.f('ck_suppressed_emails_reason_valid')),
    sa.ForeignKeyConstraint(['source_lead_id'], ['leads.id'], name=op.f('fk_suppressed_emails_source_lead_id_leads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppressed_emails'))
    )
    op.create_index(op.f('ix_suppressed_emails_email'), 'suppressed_emails', ['email'], unique=True)
    op.create_table('email_messages',
    sa.Column('campaign_lead_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grounding_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dropped_sentences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('to_address', sa.String(length=320), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pixel_fired', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'sent') OR (sent_at IS NOT NULL)", name=op.f('ck_email_messages_sent_requires_timestamp')),
    sa.CheckConstraint("status IN ('draft', 'sent', 'failed', 'suppressed')", name=op.f('ck_email_messages_status_valid')),
    sa.ForeignKeyConstraint(['campaign_lead_id'], ['campaign_leads.id'], name=op.f('fk_email_messages_campaign_lead_id_campaign_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_messages'))
    )
    op.create_index(op.f('ix_email_messages_campaign_lead_id'), 'email_messages', ['campaign_lead_id'], unique=False)
    op.create_index(op.f('ix_email_messages_tracking_token'), 'email_messages', ['tracking_token'], unique=True)
    op.create_table('email_events',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("event_type IN ('queued', 'sent', 'delivered', 'opened', 'clicked', 'replied', 'bounced', 'unsubscribed', 'failed')", name=op.f('ck_email_events_event_type_valid')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_email_events_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_email_events_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], name=op.f('fk_email_events_message_id_email_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_events'))
    )
    op.create_index(op.f('ix_email_events_campaign_id'), 'email_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_email_events_lead_id'), 'email_events', ['lead_id'], unique=False)
    op.create_index('ix_email_events_lead_id_occurred_at', 'email_events', ['lead_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_email_events_message_id'), 'email_events', ['message_id'], unique=False)
    op.create_table('replies',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('draft_response', sa.Text(), nullable=True),
    sa.Column('classifier_model', sa.String(length=80), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("intent IN ('interested', 'needs_info', 'not_now', 'wrong_person', 'unsubscribe')", name=op.f('ck_replies_intent_valid')),
    sa.CheckConstraint('(approved IS FALSE) OR (approved_at IS NOT NULL)', name=op.f('ck_replies_approval_timestamped')),
    sa.CheckConstraint('confidence IS NULL OR confidence BETWEEN 0 AND 1', name=op.f('ck_replies_confidence_in_range')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_replies_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_replies_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], name=op.f('fk_replies_message_id_email_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replies'))
    )
    op.create_index(op.f('ix_replies_campaign_id'), 'replies', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_replies_intent'), 'replies', ['intent'], unique=False)
    op.create_index(op.f('ix_replies_lead_id'), 'replies', ['lead_id'], unique=False)
    op.create_table('score_history',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_event_id', sa.Uuid(), nullable=True),
    sa.Column('old_score', sa.Integer(), nullable=True),
    sa.Column('new_score', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('new_score BETWEEN 0 AND 100', name=op.f('ck_score_history_new_score_in_range')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_score_history_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['email_events.id'], name=op.f('fk_score_history_trigger_event_id_email_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_history'))
    )
    op.create_index(op.f('ix_score_history_created_at'), 'score_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_score_history_lead_id'), 'score_history', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_history_lead_id'), table_name='score_history')
    op.drop_index(op.f('ix_score_history_created_at'), table_name='score_history')
    op.drop_table('score_history')
    op.drop_index(op.f('ix_replies_lead_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_intent'), table_name='replies')
    op.drop_index(op.f('ix_replies_campaign_id'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_email_events_message_id'), table_name='email_events')
    op.drop_index('ix_email_events_lead_id_occurred_at', table_name='email_events')
    op.drop_index(op.f('ix_email_events_lead_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_campaign_id'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_email_messages_tracking_token'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_campaign_lead_id'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_suppressed_emails_email'), table_name='suppressed_emails')
    op.drop_table('suppressed_emails')
    op.drop_index(op.f('ix_lead_scores_total_score'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_status'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_campaign_leads_lead_id'), table_name='campaign_leads')
    op.drop_index(op.f('ix_campaign_leads_campaign_id'), table_name='campaign_leads')
    op.drop_table('campaign_leads')
    op.drop_index('ix_leads_job_title', table_name='leads')
    op.drop_index(op.f('ix_leads_discovery_run_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_discovery_runs_icp_id'), table_name='discovery_runs')
    op.drop_table('discovery_runs')
    op.drop_index(op.f('ix_campaigns_icp_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('icps')
    op.drop_index('ix_companies_industry_region', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
